<script setup>
import Head from '@/components/Head.vue'
import Footer from '@/components/Footer.vue'
</script>

<template>
  <main>
    <Head/>

    <section class="policy">
      <h2>Privacy Policy</h2>
      <p>This website has been created for personal and professional purposes, to show projects and to allow contact with its author. The following details how the information of the users who visit it is treated.</p>
      <h3>1. Responsible for the site</h3>
      <p>This site is managed by <span>Pedro Rizquez</span>, software developer. You can contact directly through the form available in the contact section.</p>
      <h3>2. Information that is collected</h3>
      <h4>Contact form</h4>
      <p>If you choose to contact us using the form available on the site, you will be asked for basic information such as your name, email address and a message.</p>
      <p>This information is not stored in databases and is only used to respond to your request. The message is sent directly to an email address of the administrator.</p>
      <h3>3. Cookies and third party technologies</h3>
      <p>This site does not set cookies directly.</p>
      <p>However, by being hosted by Netlify and possibly using services such as Google Fonts fonts or other external resources, it is possible that technical or performance cookies may be generated by third parties.</p>
      <p>We recommend you consult the privacy policies of these services for more information:</p>
      <ul>
        <li><a href="https://www.netlify.com/privacy/" target="_blank">Netlify Privacy Policy ></a></li>
        <li class="space-up"><a href="https://policies.google.com/privacy" target="_blank">Google Fonts Privacy Policy ></a></li>
      </ul>
      <h3>4. Use of information</h3>
      <p>The information provided through the form is only used to respond to enquiries. It is not shared, sold or distributed to third parties.</p>
      <h3>5. Links to other sites</h3>
      <p>This site may contain links to external sites (such as GitHub or other portfolios). We are not responsible for the privacy practices of those sites.</p>
      <h3>6. Changes to this policy</h3>
      <p>This policy may be updated from time to time. It is recommended that it be reviewed periodically.</p>
      <p class="update">Last updated: March 2025</p>
    </section>

    <Footer/>
  </main>
</template>

<style scoped>
.policy {
  padding: 0px 300px;
}
.policy ul li::marker {
  color: var(--text-100);
}
.policy p, a {
  font-size: 1.3rem;
  color: var(--text-100);
  text-align: justify;
  font-weight: lighter;
}
.policy a {
  text-decoration: none;
}
.policy span {
  font-weight: bolder;
}
.policy h2, h3, h4 {
  color: var(--primary-100);
  font-weight: lighter;
}
.policy h2 {
  font-size: 2.9rem;
}
.policy h3 {
  font-size: 2rem;
}
.policy h4 {
  font-size: 1.5rem;
}
.policy .space-up {
  padding-top: 10px;
}
.policy .update {
  padding-top: 50px;
  text-align: right;
  font-style: oblique;
}

@media (max-width: 1000px) {
  .policy {
    padding: 0px 200px;
  }
}

@media (max-width: 768px) {
  .policy {
    padding: 0px 80px;
  }
  .policy h2 {
    font-size: 1.6rem;
  }
  .policy h3 {
    font-size: 1.3rem;
  }
  .policy h4 {
    font-size: 1.1rem;
  }
  .policy p, a {
    font-size: 0.95rem;
  }
  .policy .update {
    text-align: center;
  }
}

@media (max-width: 480px) {
  .policy {
    padding: 0px 30px;
  }
  .policy h2 {
    font-size: 1.4rem;
  }
  .policy h3 {
    font-size: 1.15rem;
  }
  .policy h4 {
    font-size: 1rem;
  }
  .policy p, a {
    font-size: 0.9rem;
    text-align: justify;
  }
  .policy .update {
    font-size: 0.85rem;
    padding-top: 40px;
  }
}
</style>